#!/bin/bash

# Save this file as ~/.config/yadm/bootstrap and make it executable. It will
# execute all executable files (excluding templates and editor backups) in the
# ~/.config/yadm/bootstrap.d directory when run.

set -eu

print_error() {
	printf '%s%s%s\n' "$(tput setaf 1)" "$1" "$(tput sgr0)" 1>&2
} && export -f print_error

abort() {
	print_error "$1"
	exit 1
} && export -f abort


# Directory to look for bootstrap executables in
declare -rx YADM_DIR="${HOME}/.config/yadm"
declare -rx BOOTSTRAP_DIR="${YADM_DIR}/bootstrap.d"
declare -rx PACKAGE_DIR="${YADM_DIR}/package_lists"

if [[ ! -d "$BOOTSTRAP_DIR" ]]; then
    echo "Error: bootstrap directory '$BOOTSTRAP_DIR' not found\n" >&2
    exit 1
fi

# Update origin URL to use SSH
echo "Updating the yadm repo origin URL\n"
yadm remote set-url origin "git@github.com:JoaoPPinto/dotfiles.git"

# Set yadm hooks and initialize submodules
printf "Setting yadm hooks and initializing submodules\n"
yadm gitconfig core.hooksPath "${YADM_DIR}"/hooks
yadm submodule update --recursive --init

printf "Removing original zsh config files\n"
original_zsh_files=( "${HOME}/.zshrc" "${HOME}/.zprofile" "${HOME}/.zsh_history")
for file in "${original_zsh_files[@]}"; do
  rm -rf "${file}"
done

# set zsh as shell
if ! echo "${SHELL}" | grep -q '/zsh'; then
	rpm -q zsh || sudo dnf install --assumeyes --quiet zsh
	sudo chsh -s "$(command -v zsh)" "$(whoami)"
	abort "Restart shell so that zsh environment is setup. Then re-run 'yadm bootstrap'"
else
	echo "zsh is already set as your default shell"
fi

# Run all bootstrap scripts in bootstrap.d
find -L "$BOOTSTRAP_DIR" -type f | sort | while IFS= read -r bootstrap; do
    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
        if ! "$bootstrap"; then
            abort "Error: bootstrap '$bootstrap' failed"
        fi
    fi
done

