hwdec=auto
vo=gpu-next
profile=gpu-hq
scale=ewa_lanczos

dither-depth=auto
deband=yes
deband-iterations=4
deband-threshold=35
deband-range=16
deband-grain=4

target-colorspace-hint=yes

ytdl-format="bestvideo[height<=?1080]+bestaudio/best"
script-opts-append=ytdl_hook-ytdl_path=yt-dlp
